import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import NavBar from "../components/NavBar"
import logo from '../public/logo.svg'
import so from '../public/So.svg'
import gish from '../public/Gish.svg'
import racho from '../public/Racho.svg'
import jackson from '../public/Jackson.svg'
import nyambe from '../public/Nyambe.svg'
import nguyen from '../public/Nguyen.svg'
import freeland from '../public/Freeland.svg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Team HBV Conference 2021</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/teamhbv.svg" />
      </Head>
      <NavBar />
      <div className={styles.container}>
        <main className={styles.main}>
          <div className={styles.banner}>
            <div className={styles.info}>
              <h2>The 13th Annual Team HBV Conference</h2>
              <h1 className={styles.title}>
                The Post Pandemic Future <br/> of Global Health
              </h1>
              <p>October 16 & 17 from 10:00am to 3:00pm PDT</p>
              <button id="schedule"><a href="https://stanford.zoom.us/meeting/register/tJAlduihrTIuEtwk4vBx-yBouu5X8JgiVGps" target="_blank" rel="noreferrer">Join Now!</a></button>
            </div>
            <Image src="/logo.svg" height={375} width={375}/>
          </div>

          <div className={styles.schedule}>
            <h2>Day 1 Event Schedule</h2>
            <p>Saturday, October 16 (all times in PDT)</p>
            <div className={styles.speaker}>
              <Image src={so} />
              <div className={styles.text}>
                <h3>Samuel So, MD</h3>
                <p>ALC Executive Director</p>
              </div>
              <p className={styles.times}>10:30am - 11:00am</p>
            </div>
            <div className={styles.speaker}>
              <Image src={gish}/>
              <div className={styles.text}>
                <h3>Robert Gish, MD</h3>
                <p>Co-Founder of VVHA</p>
              </div>
              <p className={styles.times}>11:00am - 11:30am</p>
            </div>
            <div className={styles.speaker}>
              <Image src={racho}/>
              <div className={styles.text}>
                <h3>Rhea Racho</h3>
                <p>Advocacy Training</p>
              </div>
              <p className={styles.times}>11:30am - 12:30pm</p>
            </div>
            <div className={styles.speaker}>
              <Image src={jackson}/>
              <div className={styles.text}>
                <h3>Michaela Jackson</h3>
                <p>Advocacy Training</p>
              </div>
              <p className={styles.times}>11:30am - 12:30pm</p>
            </div>
            <div className={styles.speaker}>
              <Image src={logo}/>
              <div className={styles.text}>
                <h3>Conference Project</h3>
                <p>Collegiate Advisory Board</p>
              </div>
              <p className={styles.times}>1:30pm - 3:00pm</p>
            </div>

            <h2>Day 2 Event Schedule</h2>
            <p>Sunday, October 17 (all times in PDT)</p>
            <div className={styles.speaker}>
              <Image src={nyambe}/>
              <div className={styles.text}>
                <h3>Monde Nyambe</h3>
                <p className={styles.monde}>Coalition Against Hepatitis for People of African Origin</p>
              </div>
              <p className={styles.times}>10:15am - 11:15am</p>
            </div>
            <div className={styles.speaker}>
              <Image src={nguyen}/>
              <div className={styles.text}>
                <h3>Tung Nguyen, MD</h3>
                <p>AAPI Advisor to Barack Obama</p>
              </div>
              <p className={styles.times}>11:15am - 11:45am</p>
            </div>
            <div className={styles.speaker}>
              <Image src={freeland}/>
              <div className={styles.text}>
                <h3>Catherine Freeland</h3>
                <p>Hepatitis B Foundation</p>
              </div>
              <p className={styles.times}>12:30pm - 1:00pm</p>
            </div>
          </div>

          <div className={styles.projectInfo} id="project">
            <h2>Conference Project</h2>
            <div className={styles.projects}>
              <a href="https://rpark23.github.io/hepbapp/" target="_blank" rel="noreferrer">
                <div className={styles.project}>
                  <Image src={logo} />
                  <h4>Hep B Quiz Game</h4>
                </div>
              </a>
              <div className={styles.project}>
                <div className={styles.template}>
                  <h4>Your <br/> Project!</h4>
                </div>
              </div>
            </div>
          </div>
        </main>
      </div>
    </>
  )
}
